### ISSUE TITLE
Bug on mongoose

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/ListBot#58] opened 2020-10-06 13:31 UTC
> (node:48710) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/
    at NativeConnection.Connection.openUri (/Users/tomassirio/Bots/DiscordBot/node_modules/mongoose/lib/connection.js:800:32)
    at /Users/tomassirio/Bots/DiscordBot/node_modules/mongoose/lib/index.js:341:10
    at /Users/tomassirio/Bots/DiscordBot/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/Users/tomassirio/Bots/DiscordBot/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Mongoose.connect (/Users/tomassirio/Bots/DiscordBot/node_modules/mongoose/lib/index.js:340:10)
    at _callee$ (/Users/tomassirio/Bots/DiscordBot/build/utils/mongoose.js:55:31)
    at tryCatch (/Users/tomassirio/Bots/DiscordBot/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/tomassirio/Bots/DiscordBot/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/Users/tomassirio/Bots/DiscordBot/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/Users/tomassirio/Bots/DiscordBot/build/utils/mongoose.js:3:103)
    at _next (/Users/tomassirio/Bots/DiscordBot/build/utils/mongoose.js:5:194)
    at /Users/tomassirio/Bots/DiscordBot/build/utils/mongoose.js:5:364
    at new Promise (<anonymous>)
    at Object.<anonymous> (/Users/tomassirio/Bots/DiscordBot/build/utils/mongoose.js:5:97)
    at Object.init (/Users/tomassirio/Bots/DiscordBot/build/utils/mongoose.js:69:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:48710) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:48710) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by trybick** [comment] 2020-10-06 13:37
I think you need to login to Mongo Atlas and add your IP to the whitelist in settings

**Comment by tomassirio** [comment] 2020-10-06 13:41
I think it was an issue on my configuration. Couldn't keep up with the changes on the repo LOL

**Comment by tomassirio** [comment] 2020-10-06 13:49
The Ip's are correctly white listed. Yet the error is there

**Comment by trybick** [comment] 2020-10-06 13:52
Probably related to the connection URL string - I would recopy the connection URL from the Atlas console and check username and password are valid

**Comment by tomassirio** [comment] 2020-10-06 14:06
Tried that as well. Changed the whole URL string connection but i'm getting the same error

**Comment by trybick** [comment] 2020-10-06 14:09
I think I had the same thing happen in my project with that whitelist error lol. I think I solved it by creating a new user account and password from the console and using that, in case that helps

**Comment by tomassirio** [comment] 2020-10-06 14:18
I guess it's because i'm using cloud mongo

**Comment by tomassirio** [comment] 2020-10-06 14:38
Ok, so i created a hardcoded Mongo URL and i was able to bypass the issue. So my wild guess is that the creation of the productionMongoUrl (and dev too) are failing somewhere

**Comment by dshah2012** [comment] 2020-10-07 00:06
The error persist in the repo. I cloned the master and I am running using docker-compose. I guess you need to add the IP address in the cluster's IP whitelist. 

Note: I have not provided any username and pasword for the db in the environment. It is running in default mode.
Is it necessary to provide any value for the mongo DB credentials. As I have read in some blogs that, sometimes it might be the cause this error is occuring.

**Comment by tomassirio** [comment] 2020-10-07 12:11
I whitelisted every ip (by whitelisting 0.0.0.0) so that doesn't seem to be the issue. The hardcoded URL however worked fine

**Comment by rgroves** [comment] 2020-10-24 18:08
Was this a user configuration issue or is it still something that needs to be looked into? If it still needs to be looked into can someone provide clear steps to reproduce the issue in question. Thanks!

**Comment by tomassiriouala** [comment] 2020-10-24 23:32
I don't know what it was, I just put the URL hardcoded on a file and it worked. Can't remember more

**Comment by rgroves** [comment] 2020-10-25 02:58
Okay, I'm going to close this out then.

**Closed as completed by rgroves** 2020-10-25 02:58 UTC
Labels: bug, help wanted, hacktoberfest, bugfix
