### ISSUE TITLE
[BUG] Saving the same doc multiple times in parallel

### ISSUE THREAD

**Issue by vitasenka** [tomassirio/ListBot#158] opened 2020-10-31 12:42 UTC
When user calls add command in a new channel for the first time, mongoose throws the following error:
UnhandledPromiseRejectionWarning: ParallelSaveError: Can't save() the same doc multiple times in parallel.

My guess: 
If you call add command in a new channel, bot calls .save() function two times. First time in channel-repository.js and second time in add.js. The first save is called when items array is empty, the second one is called after we push an item to the array.
But, since save function is async, bot first pushes the item and then calls save function two times.

*** This error only happens if the channel is not in the database!

**Comment by RazCrimson** [comment] 2020-10-31 18:41
I guess, we are missing a await for some promise in the codebase.

**Comment by rgroves** [comment] 2020-10-31 19:21
Looks like the issue is in `ChannelRepository.create`.

In `src/commands/add.js` [it does await](https://github.com/tomassirio/ListBot/blob/8f9172aec3e52d8590bf4b47fd5c33a162e5814f/src/commands/add.js#L25) the call to `ChannelRepository.findOrCreate`, but in `src/repositories/channel-repository.js` in `findOrCreate` if the channel does not exist it calls `create` and create should be returning a Promise by doing `return channel.save()` instead it is just doing `return channel` (see [here](https://github.com/tomassirio/ListBot/blob/8f9172aec3e52d8590bf4b47fd5c33a162e5814f/src/repositories/channel-repository.js#L28)).

The try/catch block and final return need to be refactored a bit.

**Comment by rgroves** [comment] 2020-10-31 19:22
Anyone want to take this one on?

**Comment by RazCrimson** [comment] 2020-11-01 10:15
@rgroves I will try taking it on.

**Comment by rgroves** [comment] 2020-11-01 16:10
I've assigned you to this issue. Thanks @RazCrimson!

**Comment by rgroves** [comment] 2020-12-22 18:12
@RazCrimson let me know if you are still working on and able to tackle this. If not I'll remove you from assignees and pick it up myself.

**Comment by RazCrimson** [comment] 2020-12-23 00:52
@rgroves Oof. I totally forgot about this due to my exams. Will finish it and make a PR soon.

Sorry for the delay 😓

**Comment by rgroves** [comment] 2020-12-23 03:14
No worries. Thanks for the update.

**Comment by RazCrimson** [comment] 2020-12-23 15:59
@rgroves I just took a look at the code. ~~But wont returning a promise make `ChannelRepository.findOrCreate` inconsistent?
Because when we call `ChannelRepository.find` it returns a channel object while `ChannelRepository.create` returns a channel object with is not created yet(but will be created. So if you edit the object and save it, it might cause Parallel Save.~~

Is it fine to just add a await?
Also should I rethrow the exception in the catch block?
``` javascript
        try {
            await channel.save()
            console.log('Stored', channel)
        } catch (e) {
            console.error(e)
        }

        return channel
 ```

**Comment by rgroves** [comment] 2020-12-23 17:49
For now, I would just model the behavior of the `ChannelRepository.create` method like `ChannelRepository.find`; where you return the await'ed value from `save` and in the `catch` just log the error and return `null`. Something like:
```
        try {
            return await channel.save()
        } catch (e) {
            console.error(e)
            return null
        }
```

To be honest, the entire codebase really needs better error handling and testing. I'm going to work on getting testing in place and that in turn should require getting better error handling in place. So, for now, I wouldn't stress to much about whether it should re-throw or not. That'll get worked out as the code is refactored for automated testing.

Some manual testing will be in order for sure after this change.

**Comment by rgroves** [comment] 2020-12-23 18:11
Just wanted to check before merging, did you put this through some manual testing?

I believe the repro steps for the original issue would be:
1. Create a new channel
2. Issue an `$add` command in that new channel

Before the fix that would cause a ParallelSaveError to be logged.

If you're able to run a few tests on existing channels and a new channel to ensure things are in working order that'd be great. If not, I can pull your change down and do some manual testing when I have some time later today.

**Comment by RazCrimson** [comment] 2020-12-23 18:52
I did test it on a new channel. Didn't seem to cause any problems.

**Closed as completed** 2020-12-23 18:54 UTC
Labels: bug
