### ISSUE TITLE
[BUG] Select commands no longer functioning

### ISSUE THREAD

**Issue by MMFW** [tomassirio/ListBot#168] opened 2020-12-18 21:58 UTC
**Describe the bug**
2-3 days ago I tested this bot on my server and it worked. Now the following commands (that I've tested) no longer work.
$list
$add
$multi-add
I am unsure if $remove works as the other functions do not.

The following functions have been tested as working:
$help
$ping 

**To Reproduce**
I've kicked and re-invited the bot with the same results.

**Comment by rgroves** [comment] 2020-12-18 22:25
If possible can you provide any error messages (if any) that were logged from the bot instance you are running on your server.

I know you mentioned and I see the same behavior seems to be happening in the SirioBots Discord channel, but I don't own that instance and I'm unable to reproduce in my development environment with the latest code from this repo. Having any error messages might provide some clues as to what is happening.

**Comment by rgroves** [comment] 2020-12-18 22:45
Spoke with @MMFW over on the SirioBots Discord server and it turns out the official ListBot is being used, not the user's own bot instance. 

Everything looks in working order with the most recent ListBot code on my dev server, so I believe the official ListBot instance has either a configuration issue or the database backing it may be down?

I'm hoping @tomassirio can chime in with what they've found through digging into the official ListBot instance and maybe we can do some simulation of the same factors that caused the failure so that we can build better error handling and user feedback into ListBot so that it better conveys to the user that there is an issue.

**Comment by tomassirio** [comment] 2020-12-18 23:15
I pulled updates changes from the repo and I got an error with the mongodb connection. I'll try to fix it this weekend. Sorry for the inconvenience

**Comment by rgroves** [comment] 2020-12-21 18:29
I'm going to close this out since it was a problem with the official ListBot instance and not a code issue.

@tomassirio please reopen if you want to keep this as a reminder to check on the db connection of the official ListBot instance. Or if it's not just a config issue and there really is an issue with the code please document it here and we can address it further.

**Closed as completed by rgroves** 2020-12-21 18:29 UTC
Labels: NotAnIssue
